--PHP-alt-<?php echo("$random_hash\r\n") ?>
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

<?php
/**
 * Request information message
 * Email to broker when a browsing user request for more information about a listing property
 */
?>

Greeting,
While browsing on your site at <?php echo $_SERVER['HTTP_HOST'] ?>, the listing at 
<?php echo $metadata->address?> (<?php echo $metadata->ref_number ?>) catches someone's attention.

This is the information sent:
<?php
foreach ($data as $key => $value) {
    echo($key . ': ' . $value . "\r\n");
}
?>
You are at one step to close this sale.

This prospect has been generated by your <?php echo(SI_NAME) ?> service.


--PHP-alt-<?php echo("$random_hash\r\n") ?>
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit

<html>
    <body style="text-align:center;background-color:#fcfcfc;">
        <table cellpadding="20" cellspacing="0" border="0" style="width:600px;">
            <tr>
                <td style="border:solid 1px #ccc;background-color:#fff;">
                    <h2>Greeting,</h2>

                    <p>While browsing on your site at <?php echo $_SERVER['HTTP_HOST'] ?>, the listing at 
                    <?php echo $metadata->address?> (<?php echo $metadata->ref_number ?>) catches someone's attention.</p>

                    <table cellspacing="0" cellpadding="10" border="0">
                        <thead>
                            <tr><td style="border-bottom:solid 1px #ccc;">&nbsp;</td><td style="background-color:#363636;color:#fff;border-bottom:solid 1px #ccc;text-transform:uppercase;text-align:center;font-size:18px">This is the information sent</td></tr>
                        </thead>
                        <?php
                        foreach ($data as $item) {
                            echo('<tr valign="top">');
                            echo('<td style="background-color:#E0E0E0;font-style:italic;text-align:right;border-left:solid 1px #ccc;border-bottom:solid 1px #ccc;">' . $item['label'] . ':</td>');
                            echo('<td style="font-weight:bold;border-right:solid 1px #ccc;border-bottom:solid 1px #ccc;">' . $item['value'] . '</td>');
                            echo('</tr>');
                        }
                        ?>
                    </table>

                    <p>You are at one step to close this sale.</p>
                    
                    <p>This prospect has been generated by your <?php echo(SI_NAME) ?> service.</p>
                </td>
            </tr>
        </table>
    </body>
</html>


--PHP-alt-<?php echo($random_hash) ?>--